### ISSUE TITLE
Stopped working?

### ISSUE THREAD

**Issue by DigibitDK** [dbkynd/twitch-logger-docker#3]
Hi dbkynd

Your program used to work fine (Well, a lot of errors in log, but still), but now I can't seem to make it work as normal.

I'm monitoring around 1800 channels, but now it seems to do no logging anymore, unless it only a few channels in the list.
Edit: Might be working with 1800 channels again ... Seems a bit random whatever it works or not.

Some examples from log:

Timezone: 'Europe/Copenhagen'
Timestamp Format String: 'HH:mm:ss'
Filename Date Pattern: 'YYYY-MM-DD'
Logging RAW IRC: false
Zipping Old Logs: false
Using Chatty Styling: false
Using Logstash Formatting: false
[16:46:09] Connected to Twitch
[16:46] error: No response from Twitch.
[16:46:13] Disconnected from Twitch
[16:46] error: Could not connect to server. Reconnecting in 1 seconds..
[16:46:13] Attempting to reconnect to Twitch
[16:46:15] Connected to Twitch
[16:46:16] Disconnected from Twitch
[16:46] error: Could not connect to server. Reconnecting in 1 seconds..
[16:46:16] Attempting to reconnect to Twitch
[16:46] error: No response from Twitch.
(... etc.)

(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.

Trace
    at Object.consoleCall (<anonymous>)
    at client.EventEmitter.addListener (/app/node_modules/tmi.js/lib/events.js:146:25)
    at /app/node_modules/tmi.js/lib/commands.js:263:18
    at /app/node_modules/tmi.js/lib/client.js:1183:9
    at new Promise (<anonymous>)
    at client._sendCommand (/app/node_modules/tmi.js/lib/client.js:1161:12)
    at client.join (/app/node_modules/tmi.js/lib/commands.js:251:21)
    at Object.fn (/app/node_modules/tmi.js/lib/client.js:185:34)
    at queue.next (/app/node_modules/tmi.js/lib/timer.js:30:8)
    at Timeout._onTimeout (/app/node_modules/tmi.js/lib/timer.js:32:14)

Best regards
Michael.

**Comment by NoodlesStamps** [comment]
I had the same situation, It was working fine until recently, but after resetting the environment, the error started to occur, I got the error "No response from Twitch."
Works fine for one channel only, but error occurs for two or more channels

I wonder if the specification have changed on the Twitch side or if it is due to blocking by IP?

Does anyone else have it working?
